# Используем Ubuntu 20.04
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Устанавливаем инструменты сборки и Go
RUN apt-get update && \
    apt-get install -y build-essential curl git wget ca-certificates gcc g++ make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Устанавливаем Go 1.24
RUN wget https://go.dev/dl/go1.24.4.linux-amd64.tar.gz -O /tmp/go1.24.4.tar.gz && \
    tar -C /usr/local -xzf /tmp/go1.24.4.tar.gz && \
    rm /tmp/go1.24.4.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /data
